#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MEMORY_MAX_SIZE 0xffff
#define MEMORY_ROM_SIZE 0x0000
#define MEMORY_RAM_SIZE (MEMORY_MAX_SIZE-MEMORY_ROM_SIZE)

#define M1_FETCH_HALF_CYCLES 6

#endif //CONSTANTS_H
